const EVENT_TYPES = {
  ECHO: 'EVENT_TYPES/ECHO',
  MESSAGE: 'EVENT_TYPES/MESSAGE',
  POSTBACK: 'EVENT_TYPES/POSTBACK',
  DELIVERY: 'EVENT_TYPES/DELIVERY',
  READ: 'EVENT_TYPES/READ',
  OPTIN_AUTH: 'EVENT_TYPES/OPTIN_AUTH',
  REFERRAL: 'EVENT_TYPES/REFERRAL',
  ATTACHMENTS: 'EVENT_TYPES/ATTACHMENTS',
  QUICK_REPLY: 'QUICK_REPLY',
  ACCOUNT_LINKING: 'ACCOUNT_LINKING'
};

export default EVENT_TYPES;
